### ISSUE TITLE
PackagesNotFoundError when install ADCME 

### ISSUE THREAD

**Issue by zoumuda** [kailaix/ADCME.jl#44]
There is an error when I install ADCME in Julia 1.0. I need help. Thanks.

│ PackagesNotFoundError: The following packages are not available from current channels:
│
│   - zip
│
│ Current channels:
│
│   - https://repo.anaconda.com/pkgs/main/win-64
│   - https://repo.anaconda.com/pkgs/main/noarch
│   - https://repo.anaconda.com/pkgs/r/win-64
│   - https://repo.anaconda.com/pkgs/r/noarch
│   - https://repo.anaconda.com/pkgs/msys2/win-64
│   - https://repo.anaconda.com/pkgs/msys2/noarch
│
│ To search for alternate channels that may provide the conda package you're
│ looking for, navigate to

**Comment by kailaix** [comment]
Are you using Windows? Unfortunately, the current version does not support windows. I’ll add support for the next version.

**Comment by zoumuda** [comment]
That's good. Thank you.

**Comment by kailaix** [comment]
Hi @zoumuda , the latest version (0.5.3) now supports Windows. Here is a video how to install  and configure it on Windows: https://youtu.be/Vsc_dpyOD6k

**Comment by zoumuda** [comment]
> Hi @zoumuda , the latest version (0.5.3) now supports Windows. Here is a video how to install and configure it on Windows: https://youtu.be/Vsc_dpyOD6k

Thank you so much for you kind help.
