### ISSUE TITLE
fc() cant be  labeled when initialising the weights

### ISSUE THREAD

**Issue by acse-ncv19** [kailaix/ADCME.jl#49]
config = [20, 20, 20, 20, 20, 20, 20, 20, 1]
θ = Variable(fc_init([2; config]))

u_nn = squeeze(fc(train_input, config, θ, "concave")) + 1

I got this kind of code but it only runs if i choose between labling the NN of initialising the weights.  When doing both I get this error:

ERROR: LoadError: MethodError: no method matching ae(::PyCall.PyObject, ::Array{Int64,1}, ::PyCall.PyObject, ::String)

**Comment by kailaix** [comment]
`fc(train_input, config, θ)` doesn't need a label. You can regard `θ` as its label if you wish. The existence of labels is to mark different neural networks, but since you provide `θ` to the neural network, the neural network is uniquely defined by `θ`.

**Comment by acse-ncv19** [comment]
thank you very much for this answer. This is very helpful to know.
