### ISSUE TITLE
cannot install ADCME with GPU support

### ISSUE THREAD

**Issue by ADharaUTEXAS123007** [kailaix/ADCME.jl#57]
julia> ENV["GPU"] = 1
1

julia> Pkg.build("ADCME")
   Building Conda \u2500\u2192 `~/.julia/packages/Conda/3rPhK/deps/build.log`
   Building PyCall \u2192 `~/.julia/packages/PyCall/zqDXB/deps/build.log`
   Building CMake \u2500\u2192 `~/.julia/packages/CMake/ULbyn/deps/build.log`
   Building HDF5 \u2500\u2500\u2192 `~/.julia/packages/HDF5/hPEcL/deps/build.log`
   Building FFTW \u2500\u2500\u2192 `~/.julia/packages/FFTW/DMUbN/deps/build.log`
   Building ADCME \u2500\u2192 `~/.julia/packages/ADCME/DBZ10/deps/build.log`
\u250c Error: Error building `ADCME`: 
\u2502 /usr/local/cuda/bin/nvcc
\u2502 Collecting package metadata (current_repodata.json): ...working... done
\u2502 Solving environment: ...working... done
\u2502 
\u2502 # All requested packages already installed.
\u2502 
\u2502 \u250c Warning: Pkg.installed() is deprecated
\u2502 \u2514 @ Pkg /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.4/Pkg/src/Pkg.jl:531
\u2502 \u250c Warning: Pkg.installed() is deprecated
\u2502 \u2514 @ Pkg /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.4/Pkg/src/Pkg.jl:531
\u2502 [ Info: Your Julia version is 1.4.2, current ADCME version is 0.5.9, ADCME dependencies installation path: /home/student/adhara/.julia/conda/3
\u2502 [ Info:  --------------- (1/6) Install Tensorflow Dependencies  --------------- 
\u2502 [ Info: ADCME dependencies have already been installed
\u2502 [ Info:  --------------- (2/6) Check Python Version  --------------- 
\u2502 \u250c Warning: Pkg.installed() is deprecated
\u2502 \u2514 @ Pkg /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.4/Pkg/src/Pkg.jl:531
\u2502    Building Conda \u2500\u2192 `~/.julia/packages/Conda/3rPhK/deps/build.log`
\u2502    Building PyCall \u2192 `~/.julia/packages/PyCall/zqDXB/deps/build.log`
\u2502 \u250c Info: PyCall Python version: /home/student/adhara/.julia/conda/3/bin/python
\u2502 \u2514 Conda Python version: /home/student/adhara/.julia/conda/3/bin/python
\u2502 [ Info:  --------------- (3/6) Looking for TensorFlow Dynamic Libraries --------------- 
\u2502 [ Info:  --------------- (4/6) Preparing Custom Operator Environment --------------- 
\u2502 [ Info:  --------------- (5/6) Installing GPU Dependencies --------------- 
\u2502 \u250c Warning: TensorFlow is compiled using CUDA 10.0, but you have CUDA 10.2. This might cause some problems.
\u2502 \u2514 @ Main ~/.julia/packages/ADCME/DBZ10/deps/build.jl:161
\u2502 ERROR: LoadError: UndefVarError: ROOTENV not defined
\u2502 Stacktrace:
\u2502  [1] top-level scope at /home/student/adhara/.julia/packages/ADCME/DBZ10/deps/build.jl:166
\u2502  [2] include(::String) at ./client.jl:439
\u2502  [3] top-level scope at none:5
\u2502 in expression starting at /home/student/adhara/.julia/packages/ADCME/DBZ10/deps/build.jl:143
\u2514 @ Pkg.Operations /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.4/Pkg/src/Operations.jl:899

**Comment by ADharaUTEXAS123007** [comment]
use_gpu()
ERROR: ADCME is not built against GPU. Set ENV["GPU"]=1 and rebuild GPU.
Stacktrace:
 [1] error(::String) at ./error.jl:33
 [2] use_gpu(::Nothing) at /home/student/adhara/.julia/packages/ADCME/DBZ10/src/extra.jl:400
 [3] use_gpu() at /home/student/adhara/.julia/packages/ADCME/DBZ10/src/extra.jl:399
 [4] top-level scope at REPL[10]:1

**Comment by kailaix** [comment]
Hi, that was a bug and should be fixed soon (within these two days). However, if you are not going to use GPU custom operators (writing your own GPU kernels), ADCME should work now. 
Thanks for pointing it out.

**Comment by kailaix** [comment]
Hi, you should be able to install the latest version with GPU support 
```julia
julia> ENV["GPU"] = 1
julia> using Pkg; Pkg.update("ADCME")
julia> Pkg.build("ADCME")
```
Let me know if you encounter any problems.

**Comment by ADharaUTEXAS123007** [comment]
it works. Thank you so much.
