### ISSUE TITLE
Error ：No dynamic library found 

### ISSUE THREAD

**Issue by yue-SJTU** [kailaix/ADCME.jl#59]
When testing the ADCME，there is a warning that it can't load （C:\Users\27632.julia\packages\ADCME\PJIHk\deps\CustomOps\build\adcme.dll）
but there is no such a file named “adcme.dll",and then the test is broken?
But the ADCME can be used with the sample code, also ,the warning always show

**Comment by kailaix** [comment]
Without `adcme.dll`, you will not be able to use many features of ADCME. 

Could you try 
```julia
using ADCME
ADCME.precompile(true)
```
and see if it fixed the problem?

**Comment by yue-SJTU** [comment]
> Without `adcme.dll`, you will not be able to use many features of ADCME.
> 
> Could you try
> 
> ```julia
> using ADCME
> ADCME.precompile(true)
> ```
> 
> and see if it fixes the problem?

No,it shows many mistakes, but the errors are the same
"C:\Users\27632\.julia\adcme\lib\site-packages\tensorflow_core\include\tensorflow/core/framework/op_kernel.h(19): 
fatal error C1083: 无法打开包括文件: “atomic”: No such file or directory [C:\Users\27632\.julia\packages\ADCME\PJIHk\deps\CustomOps\build\adcme.vcxproj]",
  PrintTensor.cpp
C:\Users\27632\.julia\adcme\lib\site-packages\tensorflow_core\include\tensorflow/core/framework/op_kernel.h(19): 
fatal error  C1083: 无法打开包括文件: “atomic”: No such file or directory [C:\Users\27632\.julia\packages\ADCME\PJIHk\deps\CustomOps\build\adcme.v
cxproj]
  正在生成代码...
ERROR: failed process: Process(`cmd /c 'C:\Users\27632\.julia\packages\CMake\ULbyn\deps\usr\bin\cmake.exe' --build . -j --target ALL_BUILD --config Release`, ProcessExited(1)) [1]

**Comment by yue-SJTU** [comment]
> Without `adcme.dll`, you will not be able to use many features of ADCME.
> 
> Could you try
> 
> ```julia
> using ADCME
> ADCME.precompile(true)
> ```
> 
> and see if it fixes the problem?

ok ，the problem has been solved，thank you
