### ISSUE TITLE
installation directory

### ISSUE THREAD

**Issue by jtao** [kailaix/ADCME.jl#60]
Hi Kailai,

The installation of ADCME on my laptop worked fine, but when I tried to install ADCME on a local cluster with a file quota, I noticed that ADCME ignored the JULIA_DEPOT_PATH setting and tried to install to ~/.julia. All other packages were installed under the desired path. 

Regards,
Jian

**Comment by jtao** [comment]
Here comes the error message. All other packages were installed under /scratch/user/jtao/Projects/SciML/packages

Error: Error building `ADCME`: 
│ ┌ Warning: Pkg.installed() is deprecated
│ └ @ Pkg /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.5/Pkg/src/Pkg.jl:554
│ ┌ Warning: Pkg.installed() is deprecated
│ └ @ Pkg /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.5/Pkg/src/Pkg.jl:554
│ [ Info: Your Julia version is 1.5.2, current ADCME version is 0.5.12, ADCME dependencies installation path: /home/jtao/.julia/adcme
│ [ Info:  --------------- (1/6) Install Tensorflow Dependencies  --------------- 
│ ERROR: LoadError: LoadError: IOError: chdir /home/jtao/.julia/: no such file or directory (ENOENT)
│ Stacktrace:
│  [1] uv_error at ./libuv.jl:97 [inlined]
│  [2] cd(::String) at ./file.jl:84
│  [3] top-level scope at /scratch/user/jtao/Projects/SciML/packages/ADCME/PJIHk/deps/install_adcme.jl:34
│  [4] include(::String) at ./client.jl:457
│  [5] top-level scope at /scratch/user/jtao/Projects/SciML/packages/ADCME/PJIHk/deps/build.jl:47
│  [6] include(::String) at ./client.jl:457
│  [7] top-level scope at none:5

**Comment by kailaix** [comment]
Hi, could you try the latest version v0.5.13?
You need to set the environment variable 
```
export JULIA_ADCME_DIR=/scratch/user/jtao/Projects/SciML/packages/
```

**Comment by jtao** [comment]
Hi Kailai,

It works now. Thanks!
Is there a reason why the default JULIA_DEPOT_DIR is not used?

Regards,
Jian

**Comment by kailaix** [comment]
JULIA_DEPOT_DIR is where the package manager looks for installed packages. JULIA_ADCME_DIR is where ADCME dependencies are installed and the installed files can be very large (up to GB). It is desirable to separate these two locations.
