### ISSUE TITLE
Unable to initialize a session with init(sess)

### ISSUE THREAD

**Issue by UnconvRS** [kailaix/ADCME.jl#62]
Hi,

I just installed ADCME and Julia v1.3 on my MacOS High Sierra, and I am able to run the test case with 10 random numbers up to the point of initializing a session with the "init(sess)" command. It fails with the error message below:

ERROR: MethodError: no method matching run(::PyCall.PyObject, ::Nothing)
Closest candidates are:
  run(::PyCall.PyObject, ::ADCME.NRResult) at /Users/folorode/.julia/packages/ADCME/XXrZo/src/optim.jl:286
  run(::PyCall.PyObject, ::mpi_SparseTensor) at /Users/folorode/.julia/packages/ADCME/XXrZo/src/mpi.jl:498
  run(::Base.AbstractCmd, ::Any...; wait) at process.jl:438
  ...
Stacktrace:
 [1] init(::PyCall.PyObject) at /Users/folorode/.julia/packages/ADCME/XXrZo/src/run.jl:48
 [2] top-level scope at REPL[28]:1

**Comment by kailaix** [comment]
Hi could you show the test code you are running?

**Comment by UnconvRS** [comment]
Here's the code:
`using ADCME
a = constant(rand(10))
sess = Session()
init(sess)
`

I think the problem I have comes from the fact that many of the standard packages I have on my system (eg. clang++, etc) are not available in the bin folder of my Julia python environment which is what I am using. When I ran ADCME.precompile(), I got the following output:
`CMake Error at CMakeLists.txt:2 (project):
  The CMAKE_CXX_COMPILER:

    /Users/folorode/.julia/adcme/bin/clang++

  is not a full path to an existing compiler tool.

  Tell CMake where to find the compiler by setting either the environment
  variable "CXX" or the CMake cache entry CMAKE_CXX_COMPILER to the full path
  to the compiler, or to the compiler name if it is in the PATH.


-- Configuring incomplete, errors occurred!
See also "/Users/folorode/.julia/packages/ADCME/XXrZo/deps/CustomOps/build/CMakeFiles/CMakeOutput.log".
See also "/Users/folorode/.julia/packages/ADCME/XXrZo/deps/CustomOps/build/CMakeFiles/CMakeError.log".
ERROR: failed process: Process(setenv(`/Users/folorode/.julia/packages/CMake/ULbyn/deps/usr/bin/cmake -G Ninja -DCMAKE_MAKE_PROGRAM=/Users/folorode/.julia/adcme/bin/ninja -DJULIA=/Applications/Julia-1.3.app/Contents/Resources/julia/bin/julia -DCMAKE_C_COMPILER=/Users/folorode/.julia/adcme/bin/clang -DCMAKE_CXX_COMPILER=/Users/folorode/.julia/adcme/bin/clang++ '' /Users/folorode/.julia/packages/ADCME/XXrZo/deps/CustomOps/`,["XPC_FLAGS=0x0", "HDF5_USE_FILE_LOCKING=FALSE", "PATH=/usr/local/opt/llvm/bin:/opt/local/bin:/opt/local/sbin:/Applications/Julia-1.3.app/Contents/Resources/julia/bin/:/usr/local/opt/gettext/bin:/anaconda3/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Library/TeX/texbin:/opt/X11/bin:/Users/folorode/petsc/arch-darwin-c-debug/bin", "PWD=/Users/folorode", "DISPLAY=/private/tmp/com.apple.launchd.hqFACOObHg/org.macosforge.xquartz:0", "XPC_SERVICE_NAME=0", "TERM_PROGRAM=Apple_Terminal", "PYTHONPATH=/Users/folorode/petsc/arch-darwin-c-debug/lib", "SHELL=/bin/bash", "__CF_USER_TEXT_ENCODING=0x1F5:0x0:0x0"  …  "TERM_SESSION_ID=442CD545-B8D5-414B-A908-8E135D41C1DD", "SSH_AUTH_SOCK=/private/tmp/com.apple.launchd.9nS8clsjXP/Listeners", "TF2_BEHAVIOR=1", "Apple_PubSub_Socket_Render=/private/tmp/com.apple.launchd.kWHGFUOIZh/Render", "USER=folorode", "SECURITYSESSIONID=186a8", "TERM=xterm-256color", "HOME=/Users/folorode", "TERM_PROGRAM_VERSION=404.1", "OPENBLAS_MAIN_FREE=1"]), ProcessExited(1)) [1]`

**Comment by kailaix** [comment]
Looks like your ADCME dependencies are not properly built or you do not have a compiler. 

Could you check

1. Whether  `/Users/folorode/.julia/adcme/bin/clang++` exists in your system.
2. If it doesn't, you might have not installed a compiler on your system. You may need to install xcode toolchains. Typically the command is `xcode-select --install`

**Comment by UnconvRS** [comment]
I have clang++ in this folder "/usr/local/opt/llvm/bin/clang++". It's just not accessible from the bin folder in clang++. I think this problem might have originated because I chose to use the python in my Julia environment, instead of the one I had set up with Anaconda...
That said, ADCME works fine on my Linux machine.

**Comment by kailaix** [comment]
I see. Then you might have a simple fix: just make a symbolic link
```bash
rm /Users/folorode/.julia/adcme/bin/clang++
ln -s /usr/local/opt/llvm/bin/clang++ /Users/folorode/.julia/adcme/bin/clang++
```

**Comment by UnconvRS** [comment]
Thank you, the problem has been resolved
